name: Telegram AutoPost Bot

on:
  schedule:
    - cron: '0 6 * * *'     # 9:00 МСК – стих дня
    - cron: '0 9 * * 0'     # 12:00 МСК – история (только по воскресеньям)
    - cron: '0 17 * * *'    # 20:00 МСК – молитва
  workflow_dispatch:        # позволяет запуск вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        run: python post_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
